syncfusion-content/ej2-react-docs

Jenkinsfile

documentation(EJ2-68378): Added jenkins

---

ej2-react/circular-gauge/internationalization.md
ej2-react/code-snippet/circulargauge/getting-started-cs4/app/index.jsx
ej2-react/code-snippet/circulargauge/getting-started-cs4/app/index.tsx
ej2-react/maps/markers.md
ej2-react/maps/user-interactions.md

conflicts resolved and committed.

documentation(EJ2-70868): conflicts resolved and committed.

---

ej2-react/file-manager/virtualization.md

I have resolved the liquid syntax error in the FileManager component.

documentation(ES-81178): Resolved the liquid syntax error.

---

ej2-react-toc.html

**Description**
Removed Unwanted Double quote

ES-826500: Removed unwanted Double Quote-Hotfix

---

ej2-react-toc.html

**Description**
Removed Unwanted Double quote

ES-826500: Removed unwanted Double Quote

---

ej2-react/button/getting-started.md
ej2-react/circular-gauge/gauge-pointers.md

HI @MallikaRK ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-176496-react-ej2-page-with-redirect-links

---

ej2-react/document-editor/how-to/disable-drag-and-drop.md
ej2-react/grid/columns/foreign-key-column.md
ej2-react/grid/editing/template-editing.md
ej2-react/pivotview/olap.md

Hi @Aishwarya-Ganesan 
Fixed the 404 issue links in EJ2 React documentation pages. Please check and merge the same.
Thanks,
Mallika

SEO-176934: Fixed page not found link

---

ej2-react/accordion/expand-mode.md
ej2-react/auto-complete/getting-started.md
ej2-react/chart/getting-started.md
ej2-react/document-editor/link.md
ej2-react/grid/filtering/filter-menu.md
ej2-react/numerictextbox/getting-started.md
ej2-react/spreadsheet/getting-started.md
ej2-react/uploader/chunk-upload.md

Worked on page with redirect for react.
Regards,
Sharly A.

SEO-176908 - React page with redirect

---

ej2-react/card/action-buttons.md
ej2-react/color-picker/accessibility.md
ej2-react/datepicker/strict-mode.md
ej2-react/daterangepicker/how-to/disable-the-daterangepicker-component.md
ej2-react/grid/infinite-scroll.md
ej2-react/grid/paging.md
ej2-react/installation/common-installation-errors.md
ej2-react/multi-select/getting-started.md
ej2-react/multi-select/localization.md
ej2-react/uploader/async.md

Work on page with redirect for react.
Regards,
Sharly A.

SEO-176708 - React Page with redirect

---

ej2-react/appearance/size-modes.md
ej2-react/multi-select/getting-started.md
ej2-react/rich-text-editor/audio.md

Worked on page with redirect for React changes.
Regards,
Sharly A.

SEO-177266 - React UG changes

---

ej2-react/card/getting-started.md
ej2-react/daterangepicker/globalization.md
ej2-react/multi-select/data-binding.md
ej2-react/tooltip/accessibility.md
ej2-react/treeview/getting-started.md

Hi @MallikaRK,
Worked on page with redirect.
Regards,
Sharly A.

SEO-177725 - React Page with redirect changes

---

ej2-react/accumulation-chart/title-and-sub-title.md
ej2-react/barcode/datamatrixgenerator.md
ej2-react/document-editor/chart.md
ej2-react/gantt/event-markers.md

Hi @Aishwarya-Ganesan,
Have worked on changing multiple H1, please review.
Regards,
Yvone.

SEO-177250 React Multiple H1

---

ej2-react/auto-complete/filtering.md
ej2-react/calendar/accessibility.md
ej2-react/dashboard-layout/panels/position-sizing-of-panels.md
ej2-react/introduction.md
ej2-react/pdfviewer/text-search.md

Please review the ej2 UG redirect link changes.
Thanks.
Regards,
Edith.

SEO-177303-React-ej2-page-with-redirect-links

---

ej2-react/datepicker/accessibility.md
ej2-react/datepicker/date-format.md
ej2-react/drop-down-list/getting-started.md
ej2-react/getting-started/quick-start.md
ej2-react/grid/context-menu.md

Please review the redirect link changes. 
Thanks.
Regards,
Edith.

SEO-177697-React-ej2-page-with-redirect-links

---

ej2-react/appbar/style-and-appearance.md
ej2-react/datepicker/how-to/disabled-the-datepicker-component.md
ej2-react/document-editor/getting-started.md
ej2-react/gantt/data-binding.md
ej2-react/radio-button/getting-started.md
ej2-react/rich-text-editor/styling.md
ej2-react/schedule/working-days.md
ej2-react/spreadsheet/freeze-pane.md
ej2-react/textbox/getting-started.md
ej2-react/tooltip/api-tooltipModel.md

Hi @MallikaRK,
Please find and review the changes made.
Regards,
Scholar.

SEO-177260-React-Page-WithRedirect-Links

---

ej2-react/diagram/constraints.md
ej2-react/diagram/page-settings.md
ej2-react/inplace-editor/validation.md
ej2-react/maps/user-interactions.md
ej2-react/pivotview/excel-export.md
ej2-react/timepicker/getting-started.md

Hi @MallikaRK,
Please find and review the changes made.
Regards,
Scholar.

SEO-176927-React-Redirect-Links

---

ej2-react/pdfviewer/getting-started.md
ej2-react/rich-text-editor/getting-started.md
ej2-react/schedule/recurrence-editor.md
ej2-react/spreadsheet/cell-range.md
ej2-react/spreadsheet/open-save.md
ej2-react/stock-chart/getting-started.md
ej2-react/switch/getting-started.md
ej2-react/timepicker/getting-started.md
ej2-react/toolbar/template-configuration.md

Hello, 
I have worked on links with redirects.
Kind Regards,
Beryl.

SEO-178943-React-Page-With-Redirect3

---

ej2-react/document-editor/bookmark.md
ej2-react/document-editor/find-and-replace.md
ej2-react/drop-down-list/getting-started.md
ej2-react/drop-down-list/localization.md
ej2-react/gantt/getting-started.md
ej2-react/grid/global-local.md
ej2-react/grid/print.md
ej2-react/installation/installation.md
ej2-react/licensing/license-key-generation.md

Hello,
I have worked on links with redirects.
Kind Regards,
Beryl.

SEO-178943-React-Page-With-Redirect1

---

ej2-react/accumulation-chart/getting-started.md
ej2-react/appearance/size-modes.md
ej2-react/button/getting-started.md
ej2-react/chart/getting-started.md
ej2-react/combo-box/getting-started.md
ej2-react/common/state-persistence.md
ej2-react/data/adaptors.md
ej2-react/datepicker/date-range.md
ej2-react/daterangepicker/accessibility.md
ej2-react/daterangepicker/getting-started.md

Hello,
I have worked on links with redirects.
Kind Regards,
Beryl.

SEO-178943-React-Page-With-Redirect

---

ej2-react/licensing/license-key-registration.md
ej2-react/list-box/getting-started.md
ej2-react/mention/getting-started.md
ej2-react/multi-select/checkbox.md
ej2-react/multi-select/data-binding.md
ej2-react/multi-select/getting-started.md
ej2-react/multi-select/localization.md
ej2-react/multi-select/templates.md
ej2-react/numerictextbox/formats.md

Hello,
I have worked on links with redirects.
Kind Regards,
Beryl.

SEO-178943-React-Page-With-Redirect2

---

ej2-react/heatmap-chart/getting-started.md
ej2-react/multi-select/getting-started.md

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-177700-React-dropped-keywords-issue-fixes

---

ej2-react/schedule/getting-started.md
ej2-react/sidebar/getting-started.md

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-177700-React-dropped-keywords-Master

---

ej2-react/calendar/getting-started.md
ej2-react/image-editor/getting-started.md
ej2-react/uploader/getting-started.md

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-177700-Dropped-keywords

---

ej2-react/code-snippet/pivot-table/default-cs97/app/App.jsx
ej2-react/code-snippet/pivot-table/default-cs97/systemjs.config.js

898927: Resolved the conflict files 

---

ej2-react/grid/cell.md
ej2-react/pdfviewer/getting-started.md
ej2-react/pdfviewer/open-pdf-file/from-dropbox-cloud-file-storage.md
ej2-react/pdfviewer/save-pdf-file/to-dropbox-cloud-file-storage.md

Need to resolve the conflict files
Need to resolve the conflict files
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes …

910309: Need to resolve the conflict files

---

ej2-react/pdfviewer/annotation/signature-annotation.md
ej2-react/pdfviewer/print.md

Description:
Resolved conflicts in print.md and signature-annotation.md

1234: resolving conflict react.

---

ej2-react/diagram/nodes-expandAndCollapse.md

Need to resolve the conflict files
Need to resolve the conflict files
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes …

927797: Need to resolve the conflict files

---

ej2-react/ui-kit/build-your-first-react-app-with-blocks.md
ej2-react/ui-kit/getting-started.md

**Description**
Need to update user guide documentation for the UI kit component, covering the following topics in React:
1. Overview
2. Getting Started
3. Build your first React app with our blocks

924430: Updating links in the UG for the UI Kit topic for the React platform

---

ej2-react-toc.html
ej2-react/code-snippet/chat-ui/templates/typingUsersTemplate/app/index.jsx
ej2-react/code-snippet/chat-ui/templates/typingUsersTemplate/app/index.tsx
ej2-react/code-snippet/gantt/resource-view-cs4/app/index.jsx

Need to Resolve conflict files
Need to Resolve conflict files
NA
NA
Feature matrix document updated against this feature and committed in this [common location]([https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents)](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents)&xsdata=MDV8MDJ8fDYxYWU4YmIxYWVlOTQxZjRjZTUxMDhkZDQwMzMzYWE5fDc3ZjFmZTEyYjA0OTQ5MTk4YzUwOWZiNDFlNWJiNjNifDB8MHw2Mzg3MzczMTA5MjgxOTUxNTN8VW5rbm …

936558: resolved the conflict for React docs

---

ej2-react/ai-developer-tools/copilot-extension.md
ej2-react/ai-developer-tools/mcp-server.md
ej2-react/ai-developer-tools/overview.md

Need to update the ai-developer-tools documents
[980907](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/980907/)
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in …

980907: Fixed document issues

---

ej2-react-toc.html
ej2-react/ai-coding-assistants/copilot-extension.md
ej2-react/ai-coding-assistants/mcp-server.md
ej2-react/ai-coding-assistants/overview.md
ej2-react/chart/getting-started.md
ej2-react/diagram/getting-started.md
ej2-react/gantt/getting-started.md
ej2-react/grid/getting-started.md
ej2-react/introduction.md
ej2-react/kanban/getting-started.md
ej2-react/pivotview/getting-started.md
ej2-react/rich-text-editor/getting-started.md
ej2-react/schedule/getting-started.md

Need to update ai developer tools section
[984683](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/984683/)
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding …

984683: Need to update ai developer tools section

---

ej2-react/smart-paste-button/annotation.md
ej2-react/smart-paste-button/getting-started.md
ej2-react/smart-paste-button/handling-validation.md

Need to resolved Liquid syntax error in the React Smart Paste component
[985784](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/985784/)
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not …

985784: Resolved Liquid syntax error in the React Smart Paste component
